<?php

use App\Support\Pagination\Pagination;

/** @var Pagination $pagination */
?>
<nav aria-label="Page navigation example">
	<ul class="pagination">
        <?php foreach ($pagination->getPaginationLinks() as $key => $link): ?>
			<li class="page-item <?= $pagination->getPage() === $link->getPageNumber() ? 'active' : ''; ?>">
				<a class="page-link" href="<?= $link->getLink() ?>"><?= $link->getPageNumber() ?></a>
			</li>
        <?php endforeach; ?>
	</ul>
</nav>
