<?php

use App\Model\User;
use App\Support\Pagination\Pagination;

/** @var User[] $users */
/** @var Pagination $pagination */
?>
<div class="container mt-5">
	<h3 class="pt-4">Users</h3>
    <?php if (!empty($users) && count($users) > 0) : ?>
		<table class="table">
			<thead>
			<tr>
				<th>Full Name</th>
				<th>Email</th>
				<th>Assigned issues</th>
			</tr>
			</thead>
			<tbody>
            <?php foreach ($users as $user) : ?>
				<tr>
					<td><a href="<?= $user->getLink() ?>"><?= $user->get('email') ?></a></td>
					<td><?= $user->get('email') ?></td>
					<td>
						<a href="<?= $user->getAssignedIssuesLink() ?>">(Count) issues</a>
					</td>
				</tr>
            <?php endforeach; ?>
			</tbody>
		</table>
		<div class="container">
            <?php if ($pagination->getPagesCount() > 1) : ?>
                <?php require_once BASE_PATH . '/views/partial/pagination.phtml';?>
            <?php endif; ?>
		</div>
    <?php else : ?>
		<div class="alert alert-warning">No issues. <a href="create">Create</a></div>
    <?php endif; ?>
</div>
