<?php

use App\Model\Issue;
use App\Model\User;

/** @var User[] $users */
/** @var Issue $issue */
?>
<div class="container mt-5">
	<h3 class="pt-4"><?= isset($issue) ? "Edit issue #{$issue->get('id')}" : 'New issue' ?></h3>
	<form action="" method="post">
		<div class="form-group">
			<label for="title">Title</label>
			<input type="text" class="form-control" id="title" name="title" placeholder="Enter issue title..."
				   value="<?= isset($issue) ? $issue->get('title') : '' ?>">
		</div>
		<div class="form-group">
			<label for="description">Description</label>
			<textarea class="form-control" id="description" name="description" placeholder="Enter issue description..."
			><?= isset($issue) ? $issue->get('description') : '' ?></textarea>
		</div>
		<div class="form-group">
			<label class="form-check-label" for="assignedTo">Assigned to</label>
			<select class="form-control" id="assignedTo" name="assigned_to_id">
				<option value="0">--</option>
				<?php foreach ($users as $user) : ?>
					<option value="<?= $user->get('id') ;?>"
						<?= isset($issue) && $issue->get('assigned_to_id') === $user->get('id') ? 'selected="selected"' : '' ?>
					><?= "{$user->getFullName()} ({$user->get('email')})" ?></option>
				<?php endforeach; ?>
			</select>
		</div>
		<button type="submit" class="btn btn-primary"><?= isset($issue) ? 'Save' : 'Create' ?></button>
	</form>
</div>
